### ISSUE TITLE
[TODO] comments + other

### ISSUE THREAD

**Issue by timotheecour** [h3rald/nimline#9]
- [x] would be nice if readme contained more info/docs
- [x] feature comparison with https://github.com/jackvandrunen/linenoise-nim ?
- [x] what common features are supported, eg:
* multiline support
* UTF8 support
* color support
* custom prompt, eg color prompt
* tab completion
* history handling; history sharing across sessions

**Comment by h3rald** [comment]
Darn! I was going to keep this project hidden for a while! ;) 

OK, OK, I get the picture, I'll try to prepare some docs! Thanks a lot for your interest!

**Comment by timotheecour** [comment]
isn't early feedback good ;-) ?

**Comment by h3rald** [comment]
I wrote some [reference docs](https://h3rald.com/nimline/nimline.html), have a look and see what you think!
